.default: &default
  application: {{WP_BOILERPLATE_SLUG}}
  theme_name: '{{application}}'
  repository: {{WP_BOILERPLATE_REPO}}
  url: http://{{application}}.hmdev
  wp_user: {{WP_BOILERPLATE_USER}}
  wp_email: {{WP_BOILERPLATE_EMAIL}}
  wp_site_url: http://{{application}}.hmdev/wordpress
  wp_content_dir: content
  deploy_path: {{WP_BOILERPLATE_DEPLOY_PATH}}
  public_path: {{WP_BOILERPLATE_PUBLIC_PATH}}
  database:
    host: database
    database: wp_{{WP_BOILERPLATE_SLUG}}
    username: root
    password: ''
  wp_config_constants: &default_wp_config_constants
    WP_ENVIRONMENT_TYPE: development
    WP_AUTO_UPDATE_CORE: false
    WPMS_ON: true
    WPMS_DO_NOT_SEND: true
    WPMS_MAIL_FROM: {{WP_BOILERPLATE_MAIL_FROM}}
    WPMS_MAIL_FROM_FORCE: true
    WPMS_MAIL_FROM_NAME: '{{WP_BOILERPLATE_MAIL_FROM_NAME}}'
    WPMS_MAIL_FROM_NAME_FORCE: true
    WPMS_MAILER: sendgrid
    WPMS_SENDGRID_API_KEY: {{WP_BOILERPLATE_SENDGRID_API_KEY}}
    WPMS_SENDGRID_DOMAIN: {{WP_BOILERPLATE_PRODUCTION_DOMAIN}}
    WPMS_LOGS_ENABLED: true
    WPMS_LOGS_LOG_EMAIL_CONTENT: true
    WP_MAIL_SEND_DOMAIN_WHITELIST:
      - itsahappymedium.com
    WP_MAIL_SEND_EMAIL_WHITELIST: []

staging-server:
  <<: *default
  stage: staging
  branch: development
  hostname: {{WP_BOILERPLATE_STAGING_IP}}
  user: {{WP_BOILERPLATE_STAGING_USER}}
  url: {{WP_BOILERPLATE_STAGING_URL}}
  wp_site_url: {{WP_BOILERPLATE_STAGING_URL}}/wordpress
  database:
    host: 127.0.0.1:3306
    database: wp_{{WP_BOILERPLATE_SLUG}}
    username: {{WP_BOILERPLATE_STAGING_DB_USER}}
    password: {{WP_BOILERPLATE_STAGING_DB_PASS}}
  wp_config_constants:
    <<: *default_wp_config_constants
    WP_ENVIRONMENT_TYPE: staging

production-server:
  <<: *default
  stage: production
  branch: main
  hostname: {{WP_BOILERPLATE_PRODUCTION_IP}}
  user: {{WP_BOILERPLATE_PRODUCTION_USER}}
  url: {{WP_BOILERPLATE_PRODUCTION_URL}}
  wp_site_url: {{WP_BOILERPLATE_PRODUCTION_URL}}/wordpress
  database:
    host: 127.0.0.1:3306
    database: wp_{{WP_BOILERPLATE_SLUG}}
    username: {{WP_BOILERPLATE_PRODUCTION_DB_USER}}
    password: {{WP_BOILERPLATE_PRODUCTION_DB_PASS}}
  wp_config_constants:
    <<: *default_wp_config_constants
    WP_ENVIRONMENT_TYPE: production
    GOOGLE_ANALYTICS_ID: {{WP_BOILERPLATE_GOOGLE_ANALYTICS_ID}}
    WPMS_DO_NOT_SEND: false
    WPMS_LOGS_ENABLED: false
    WPMS_LOGS_LOG_EMAIL_CONTENT: false